version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasks-management
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

